# Default values for rtsp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: antares

rtsp:
  image:
    registry:
    repository: 1mstaging.azurecr.io/rtsp-simple-server
    pullPolicy: Always
    tag: "ubuntu"

  imagePullSecrets:
    - name: azreg
  name: "rtsp"
  securityContext:
    privileged: true

httpsProxy:
  image:
    registry:
    repository: 1mstaging.azurecr.io/https-proxy
    pullPolicy: Always
    tag: "f22aefb-master"

  imagePullSecrets:
    - name: azreg
  name: "https-proxy"
  securityContext:
    privileged: true
    
podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#nodeSelector: {}
#
#tolerations: []
#
#affinity: {}
