apiVersion: v1
kind: ConfigMap
metadata:
  name: rtsp-cm
  namespace: antares
data:
  rtsp-simple-server.yml: |
    hlsSegmentCount: 10
    hlsSegmentDuration: 2s
    paths:
      back:
        source: rtsp://admin:1MRobotics@camera-back/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/back -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/back/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      front:
        source: rtsp://admin:1MRobotics@camera-front/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/front -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/front/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      back-low:
        source: rtsp://admin:1MRobotics@camera-back/Streaming/Channels/102
      front-low:
        source: rtsp://admin:1MRobotics@camera-front/Streaming/Channels/102
      lift:
        source: rtsp://admin:1MRobotics@camera-lift/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/lift -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/lift/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      kiosk:
        source: rtsp://admin:1MRobotics@camera-kiosk/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/kiosk -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/kiosk/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      lift-low:
        source: rtsp://admin:1MRobotics@camera-lift/Streaming/Channels/102
      kiosk-low:
        source: rtsp://admin:1MRobotics@camera-kiosk/Streaming/Channels/102
      outdoor-1:
        source: rtsp://admin:1MRobotics@outdoor-1/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/outdoor-1 -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/outdoor-1/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      outdoor-1-low:
        source: rtsp://admin:1MRobotics@outdoor-1/Streaming/Channels/102
      outdoor-2:
        source: rtsp://admin:1MRobotics@outdoor-2/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/outdoor-2 -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/outdoor-2/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      outdoor-2-low:
        source: rtsp://admin:1MRobotics@outdoor-2/Streaming/Channels/102
        