apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.controlapp.name }}
  labels:
    {{- include "control-app.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "control-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "control-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controlapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: [ "dotnet" ]
          args: [ "ControlApp.dll" ]
          securityContext:
            {{- toYaml .Values.controlapp.securityContext | nindent 12 }}
          image: "{{ .Values.controlapp.image.repository }}:{{ .Values.controlapp.image.tag }}"
          ports:
            - containerPort: 8084
              hostIP: 192.168.12.1
              hostPort: 8084
          imagePullPolicy: {{ .Values.controlapp.image.pullPolicy }}
          env:
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: control.url
            - name: ORCHESTRATOR_URL
              value: http://192.168.12.1:8083
            - name: ENVIRONMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: env.name
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: asp.env
