apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.lwms.name }}
  labels:
    {{- include "lwms.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      {{- include "lwms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lwms.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.lwms.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      volumes:
        - name: cert
          hostPath:
            path: /cert
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          command: [ "dotnet" ]
          args: [ "LWMS.dll" ]
          ports:
            - containerPort: 8082
              hostIP: 192.168.12.1
              hostPort: 8082
          securityContext:
            {{- toYaml .Values.lwms.securityContext | nindent 12 }}
          image: "{{ .Values.lwms.image.repository }}:{{ .Values.lwms.image.tag }}"
          imagePullPolicy: {{ .Values.lwms.image.pullPolicy }}
          volumeMounts:
            - mountPath: /cert
              name: cert
          env:
            - name: ENVIRONMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: env.name
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: asp.env
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: lwms.url
            - name: SECRET_POSTGRESQL_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: postgresql.connection
            - name: SECRET_EVENT_HUBS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: EventHubsConnection
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: AzureClientId
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: AzureClientSecret
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: AzureSubscriptionId
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: AzureTenantId
            - name: SOLARIS_URL
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: solaris.url
            - name: SECRET_AUTH0_INTERNAL_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: Auth0InternalApiClientId
            - name: SECRET_AUTH0_INTERNAL_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: Auth0InternalApiClientSecret
