apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mediaApp.name }}
  labels:
    {{- include "media-app.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      {{- include "media-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "media-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.mediaApp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostNetwork: true
      volumes:
        - name: storage
          hostPath:
            path: /storage
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          command: [ "dotnet" ]
          args: [ "MediaApp.dll" ]
          volumeMounts:
            - mountPath: /storage
              name: storage
          ports:
            - containerPort: 8081
              hostIP: 192.168.12.1
              hostPort: 8081
          securityContext:
            {{- toYaml .Values.mediaApp.securityContext | nindent 12 }}
          image: "{{ .Values.mediaApp.image.repository }}:{{ .Values.mediaApp.image.tag }}"
          imagePullPolicy: {{ .Values.mediaApp.image.pullPolicy }}
          env:
            - name: ENVIRONMENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: env.name
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: asp.env
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: antares-cm
                  key: video.url
            - name: SECRET_BLOB_STORAGE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: key-vault-secret
                  key: BlobStorageConnection

