apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-share-volume
  namespace: antares
  labels:
    type: local
spec:
  storageClassName: local-share
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/shared"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-share
  namespace: antares
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-share
