apiVersion: v1
kind: ConfigMap
metadata:
  name: rtsp-cm
  namespace: antares
data:
  rtsp-simple-server.yml: |
    paths:
      back:
        source: rtsp://admin:1MRobotics@camera-back/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/back -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/back/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
      front:
        source: rtsp://admin:1MRobotics@camera-front/Streaming/Channels/101
        runOnReady: ffmpeg -i rtsp://localhost:8554/front -c copy -f segment -strftime 1 -segment_time 60 -segment_format mp4 /storage/front/%Y-%m-%d_%H-%M-%S.mp4
        runOnReadyRestart: yes
