apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  volumes:
  - name: storage
    hostPath:
      path: /home/onemrobotics/storage
      type: Directory
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: storage
      mountPath: /storage
  hostNetwork: true
  dnsPolicy: Default