##  Coralogix Account settings
PRIVATE_KEY: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
APP_NAME: $kubernetes.namespace_name
SUB_SYSTEM: $kubernetes.container_name
ENDPOINT: api.coralogix.us

## Coralogix output settings
coralogix:
  # log_key_name: ""
  # timestamp_key_name: ""
  is_json: true
  force_compression: false
  debug: false
  proxy: {}
  #  host: localhost
  #  port: 3128
  #  user: root
  #  password: strong_pass

## Pod settings
container:
  image:
    repository: coralogixrepo/coralogix-fluentd-multiarch
    tag: v0.0.1
    pullPolicy: Always
    resources:
      requests:
        cpu: 800m
        memory: 900Mi
      limits:
        cpu: 800m
        memory: 900Mi

## Security settings
rbac:
  create: true

## Node settings
tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule

## FluentD service settings
service:
  fluentd:
    enabled: true
    port: 24224
  http:
    enabled: true
    port: 9880
  syslog:
    enabled: true
    port: 5140
  graylog:
    enabled: true
    port: 12201
  clusterIP: None
