apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kiosk.name }}
  labels:
    {{- include "kiosk.selectorLabels" . | nindent 6 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      {{- include "kiosk.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kiosk.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.kiosk.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: local-share
          persistentVolumeClaim:
            claimName: local-share
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          ports:
            - containerPort: 3000
              hostIP: 192.168.11.1
              hostPort: 3000
            # NFS
            - containerPort: 2049
              hostIP: 192.168.11.1
              hostPort: 22049
          volumeMounts:
            - mountPath: /var/lib/docker
              name: local-share
              subPath: kiosk-loader/docker
            - mountPath: /networking
              name: local-share
              subPath: networking
          securityContext:
            {{- toYaml .Values.kiosk.securityContext | nindent 12 }}
          image: "{{ .Values.kiosk.image.repository }}:{{ .Values.kiosk.image.tag }}"
          imagePullPolicy: {{ .Values.kiosk.image.pullPolicy }}
          env:
            - name: REACT_APP_API_URL
              value: http://192.168.11.1:8083
            - name: REACT_APP_CONTAINER_ID
              value: '1'
            - name: DOCKER_IMAGE
              value: 1mtest.azurecr.io/kiosk-os
            - name: DOCKER_USER
              value: kiosk
            - name: DOCKER_PASSWORD
              value: +uExAtKMj011H691pPB0mgVW5BtQY1Gg
            - name: SWITCH_MGMT_IP
              value: 192.168.9.3
            - name: SWITCH_LOGIN_PASSWORD
              value: 1MR0b0tics
